CREATE TABLE IF NOT EXISTS invites (
  id SERIAL PRIMARY KEY,
  handler_id INTEGER REFERENCES handlers(id) ON DELETE CASCADE,
  email TEXT NOT NULL,
  token_hash TEXT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  used_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW()
);
